#!/usr/bin/env python3
"""meeting-notes: Generate a structured meeting notes template."""
import sys
from pathlib import Path
from datetime import datetime

title = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else "Meeting Notes"
date = datetime.now().strftime("%Y-%m-%d %H:%M")

template = f"""# {title}
**Date:** {date}
**Location:** (fill in)
**Attendees:** (list names)

## Agenda
1.

## Discussion
-

## Action Items
- [ ]

## Next Steps
-

## Notes


---
*Generated by OpenClaw*
"""

out = Path.home() / "meeting-notes.md"
with open(out, "w") as f:
    f.write(template)
print(f"**Meeting Notes — created at {out}**")
print(template)
